import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import {PrismaClient} from "@prisma/client"

const prisma = new PrismaClient()

export async function getServerSideProps(){
  const contacts = await prisma.users.findMany()
  console.log(contacts)
  return{
    props: {
      initialContacts: contacts
    }
  }
}

export default function Home() {

  return (
    <>
      <Head>
        <title>Finance Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>First commit</h1>
      </main>
    </>
  )
}
